### ISSUE TITLE
License File?

### ISSUE THREAD

**Issue by jqnatividad** [Raduc4/gender_guesser#2]
Hi @Raduc4 ,

Would love to use your library, but I don't see a license file.

MIT License would be ideal.

Edit:
Just saw that Cargo.toml indicated an MIT License, but having a LICENSE.md file would be great just to be sure!

**Comment by Raduc4** [comment]
Hi @jqnatividad , Yes, of course, I will be able to add a License file in 1 hour or so.

**Comment by Raduc4** [comment]
@jqnatividad Done
